define [
  'angular'
  'angularRoute'
  'angularResource'
  'angularAnimate'
  'angularTouch'
  'angularStrap'
  'c/controllers'
  'd/directives'
  'f/filters'
  'p/providers'
  'r/resources'
  's/services'
], (angular) ->
  'use strict'
  angular.module 'app', [
      'ngResource'
      'ngRoute'
      'ngAnimate'
      'ngTouch'
      'mgcrea.ngStrap'
      'controllers'
      'directives'
      'filters'
      'providers'
      'resources'
      'services'
  ]